# workflow name
name: CI/CD Pipeline
#workflow triggers on push or pull
on:
  push:
    branches:
      - main
  pull_request:
# perform 2 jobs: build-test and deploy
jobs:
  build-and-test:
    #run on latest ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # fetch code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test
  # deploy on dockerhub
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # fetch latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Dockerhub log in using credentials stored in github secrets
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # build and push docker image also stoping and removing any container with the same name
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-ci-cd:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-ci-cd:latest

      # Step 4: Deploy Docker container
      - name: Deploy Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-ci-cd:latest
          docker stop nodejs-app || true
          docker rm nodejs-app || true
          docker run -d -p 3000:3000 --name nodejs-app ${{ secrets.DOCKER_USERNAME }}/nodejs-docker-ci-cd:latest
